#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if [[ $(uname) == *"MINGW"* ]]; then
  $DIR/esp-flasher-win.exe $@
elif [[ $(uname) == *"Darwin"* ]]; then
  $DIR/esp-flasher-osx $@
else
  $DIR/esp-flasher-linux $@
fi
